In [212]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt

In [213]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

#In training dataset, We have 4 features for each row. For each row, we have a target value Y#

In [214]:
# data is stored in numpy array/matrix
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [215]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [216]:
#input x,ini w,b,so,we can get a y_hat which is predicted Y#
def predict_single_loop(x,w,b):
    n=x.shape[0]
    p=0
    for i in range(n):
        p=p+x[i]*w[i]
    p=p+b
    return p

In [217]:
print(X_train[0,:],predict_single_loop(X_train[0,:],w_init,b_init))

[2104    5    1   45] 459.9999976194083


In [218]:
#This function is to predict vector number, it  is easier compare wtih predict_single_loop function. Just using np.dot()#
def predict_vector_single_loop(x,w,b):
    p=np.dot(x,w)
    p=p+b
    return p


In [219]:
print(X_train[0,:],predict_vector_single_loop(X_train[0,:],w_init,b_init))

[2104    5    1   45] 459.9999976194083


In [220]:
#Cost function for 3 rows#
def cost_function(x,y,w,b):
    m=x.shape[0]
    Cost=0
    for i in range(m):
        Cost=Cost+((np.dot(x[i],w)+b-y[i])**2)
    Cost=Cost/(2*m)
    return Cost

In [221]:
print(cost_function(X_train, y_train, w_init, b_init))

1.5578904045996674e-12


In [222]:
#Computer gradient for multi liner regression and it return derivative#
def gradient(x,y,w,b):
    # for line
    m,n=x.shape
    dj_w=np.zeros((n,))
    dj_b=0
    for i in range(m):
        
      error=np.dot(x[i],w)+b-y[i]
      for j in range(n):
        dj_w[j]=dj_w[j]+error*x[i,j]
      dj_b=dj_b+error
    dj_w=dj_w/m
    dj_b=dj_b/m
    return dj_b,dj_w


In [223]:
dj_b,dj_w = gradient(X_train, y_train, w_init, b_init)
print('dj_w:',dj_w)
print('dj_b:',dj_b)

dj_w: [-2.72623574e-03 -6.27197255e-06 -2.21745574e-06 -6.92403377e-05]
dj_b: -1.6739251122999121e-06


In [224]:
#Now we add alpga rate and iteration in the gradient descent function#
def gradient_descent(x, y, w_in, b_in, cost_function, gradient, alpha, num_iters):
    history=[]
    w=copy.deepcopy(w_in)
    b=b_in
    for i in range(num_iters):
        dj_b,dj_w=gradient(x,y,w,b)
        w=w-alpha*dj_w
        b=b-alpha*dj_b
    
        if i<100000:      # prevent resource exhaustion 
            history.append( cost_function(x, y, w, b))

        if i% math.ceil(num_iters / 10) == 0:
            print('Iteration:', i, 'Cost:',history[-1])
    return w,b,history

In [225]:
initial_w = np.zeros_like(w_init)
initial_b = 0.
alpha=5.0e-7
iteration=10000
w_final,b_final,history=gradient_descent(X_train,y_train,initial_w,initial_b,cost_function,gradient,alpha,iteration)

Iteration: 0 Cost: 2529.4629522316304
Iteration: 1000 Cost: 686.6934839275283
Iteration: 2000 Cost: 677.1889369724992
Iteration: 3000 Cost: 668.4815829959585
Iteration: 4000 Cost: 660.5035880182975
Iteration: 5000 Cost: 653.1928903567929
Iteration: 6000 Cost: 646.492709434985
Iteration: 7000 Cost: 640.3510963896543
Iteration: 8000 Cost: 634.7205229186773
Iteration: 9000 Cost: 629.5575051156565


In [226]:
print('Final_DJ_W:',w_final)
print('Final_DJ_b:',b_final)

Final_DJ_W: [ 0.21699899  0.03240792 -0.10755879 -0.5799772 ]
Final_DJ_b: -0.019077710470483216


In [227]:
for i in range(len(X_train)):
    print('Prediction:',predict_vector_single_loop(X_train[i],w_final,b_final),'ActualValue:',y_train[i])

Prediction: 430.50230063959395 ActualValue: 460
Prediction: 283.93450796752995 ActualValue: 232
Prediction: 164.52211536512178 ActualValue: 178
